# DVC Pipeline Configuration
# Versions and tracks datasets, features, models, and metrics

stages:
  # ============================================
  # FASE 1: Preparación de Datos
  # ============================================
  prepare:
    cmd: kedro run --pipeline=data_preparation_pipeline
    deps:
      - data/01_raw/movies.csv
      - data/01_raw/releases.csv
      - data/01_raw/genres.csv
      - data/01_raw/countries.csv
      - src/letterboxdml/pipelines/data_preparation_pipeline.py
    outs:
      - data/02_intermediate/releases_clean.csv
      - data/02_intermediate/countries_clean.csv
      - data/02_intermediate/genres_clean.csv
      - data/02_intermediate/min_release.csv
      - data/03_primary/final_df.csv
      - data/03_primary/integrated_data.csv
      - data/03_primary/final_df_us_2000s_2010s.parquet
    plots:
      - data/08_reporting/cleaning_process.png
      - data/08_reporting/comparative_analysis.png

  # ============================================
  # FASE 2: Feature Engineering
  # ============================================
  features:
    cmd: kedro run --pipeline=eda_pipeline
    deps:
      - data/02_intermediate/releases_clean.csv
      - data/02_intermediate/countries_clean.csv
      - data/02_intermediate/genres_clean.csv
      - data/03_primary/final_df.csv
      - src/letterboxdml/pipelines/eda_pipeline.py
    outs:
      - data/05_model_input/classification_dataset.csv
      - data/05_model_input/regression_dataset.csv
    plots:
      - data/08_reporting/quality_analysis.png
      - data/08_reporting/temporal_analysis.png
      - data/08_reporting/genre_analysis.png
      - data/08_reporting/advanced_categorical_analysis.png

  # ============================================
  # FASE 3: Entrenar Modelos de Clasificación
  # ============================================
  train_classification:
    cmd: kedro run --pipeline=classification_pipeline
    deps:
      - data/05_model_input/classification_dataset.csv
      - src/letterboxdml/pipelines/ml_modeling_pipeline.py
    outs:
      - data/06_models/classification_results.pkl
      - data/06_models/classification_metrics.pkl
    metrics:
      - data/06_models/classification_metrics.json:
          cache: false
    plots:
      - data/08_reporting/classification_results.png

  # ============================================
  # FASE 4: Entrenar Modelos de Regresión
  # ============================================
  train_regression:
    cmd: kedro run --pipeline=regression_pipeline
    deps:
      - data/05_model_input/regression_dataset.csv
      - src/letterboxdml/pipelines/ml_modeling_pipeline.py
    outs:
      - data/06_models/regression_results.pkl
      - data/06_models/regression_metrics.pkl
    metrics:
      - data/06_models/regression_metrics.json:
          cache: false
    plots:
      - data/08_reporting/regression_results.png

  # ============================================
  # FASE 5: Evaluar Modelos
  # ============================================
  evaluate:
    cmd: kedro run --pipeline=ml_modeling_pipeline
    deps:
      - data/06_models/classification_results.pkl
      - data/06_models/regression_results.pkl
      - src/letterboxdml/pipelines/ml_modeling_pipeline.py
    outs:
      - data/07_model_output/comparison_report.md
      - data/07_model_output/final_metrics.pkl
    metrics:
      - data/07_model_output/final_metrics.json:
          cache: false
    plots:
      - data/08_reporting/model_comparison.png
      - data/08_reporting/best_models_analysis.png

